### PR TITLE
Feature/sc 1134/add indicator for recognized delegates that

### PR DESCRIPTION
**Pull request by adamgoth**
### Link to Shortcut ticket:

https://app.shortcut.com/dux-makerdao/story/1134/add-indicator-for-recognized-delegates-that-are-also-cu-members

### What does this PR do?

Adds core unit member button and modal

Delegate fetch from github now looks for a `cumember.md` file in each delegate directory.  If this exists, we will display the icon and button.

### Steps for testing:

On goerli, go to delegates page. See delegate with core unit disclosure.

### Screenshots (if relevant):
Screen Shot 2022-03-22 at 9 42 36 AM

Screen Shot 2022-03-22 at 9 42 29 AM

### CODE REVIEW

**Review by rafinskipg — APPROVED** [review]
LGTM! 
- The "learn more" link does not go anywhere
- should we show also the "core unit member" on the delegate detail page?
- maybe on the little popover when hovering over a delegate image on the vote history / supporters?

**Review by philipjonsen — COMMENTED** [review]
Try this

**Comment by philipjonsen** [comment]
Maybes its this shadowdelegator causing problem? Are shadows supposed do delegate? 


shadowdelegate



CypressError
`cy.visit()` failed trying to load: http://localhost:3000/delegates?network=goerlifork We attempted to make an http request to this URL but the request failed without a response. We received this error at the network level: > Error: ESOCKETTIMEDOUT Common situations why this would fail: - you don't have internet access - you forgot to run / boot your web server - your web server isn't accessible - you have weird network configuration settings on your computer

4
CypressError
`cy.visit()` failed trying to load: http://localhost:3000/executive?network=goerlifork We attempted to make an http request to this URL but the request failed without a response. We received this error at the network level: > Error: ESOCKETTIMEDOUT Common situations why this would fail: - you don't have internet access - you forgot to run / boot your web server - your web server isn't accessible - you have weird network configuration settings on your computer

3CypressError
Timed out retrying after 40000ms: `cy.type()` failed because this element: `<textarea data-testid="poll-comment-box" maxlength="250" class="css-1uawx1e-CommentTextBox"></textarea>` is being covered by another element: `<h5 class="css-cv4mso-CardHeader">Posted ...</h5>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 40000ms: `cy.type()` failed because this element: `<textarea data-testid="poll-comment-box" maxlength="250" class="css-1uawx1e-CommentTextBox"></textarea>` is being covered by another element: `<p class="css-1hbd33i-PollOverviewCard">Posted ...</p>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 40050ms: `cy.click()` failed because this element is `disabled`: `<button disabled="" class="css-1jpy27m-MKRAmount">Continue</button>` Fix this problem, or use `{force: true}` to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 40050ms: `cy.click()` failed because this element is not visible: `<label data-testid="delegate-type-filter-show-recognized" class="css-1qp4ca6-DelegatesFilter">...</label>` This element `<label.css-1qp4ca6-DelegatesFilter>` is not visible because its parent `<div>` has CSS property: `display: none` Fix this problem, or use `{force: true}` to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 40050ms: `cy.click()` failed because this element: `<button data-testid="submit-ballot-button" class="css-1yvdtqj-SubmitBallotsButtons">2 - Sub...</button>` is being covered by another element: `<footer>...</footer>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 90000ms: `cy.type()` failed because this element: `<input aria-label="mkr-input" data-testid="mkr-input" type="number" placeholder="0.000000 MKR" lang="en" class="css-16i54n5-MKRInput" value="">` is being covered by another element: `<div data-nextjs-dialog-body="true" class="nextjs-container-errors-body">...</div>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 90050ms: `cy.click()` failed because this element: `<button data-testid="button-delegate" class="css-1nrpr8j-DelegateCard">Delegate</button>` is being covered by another element: `<div data-nextjs-dialog-content="true">...</div>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
Timed out retrying after 90050ms: `cy.click()` failed because this element: `<button data-testid="button-delegate" class="css-1qt4itn-DelegateCard">Delegate</button>` is being covered by another element: `<div data-nextjs-dialog-content="true">...</div>` Fix this problem, or use {force: true} to disable error checking. https://on.cypress.io/element-cannot-be-interacted-with

1
CypressError
`cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element. https://on.cypress.io/click

1
CypressError
`cy.exec('npx hardhat fork --network localhost --block 6349521')` failed because the command exited with a non-zero code. Pass `{failOnNonZeroExit: false}` to ignore exit code failures. Information about the failure: Code: 1 Stderr: [31mAn unexpected error occurred:[39m ProviderError: ConnectTimeoutError: Connect Timeout Error at HttpProvider.request (/__w/governance-portal-v2/governance-portal-v2/node_modules/hardhat/sr... https://on.cypress.io/exec Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Delegates Page` Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail

1
CypressError
`cy.exec('npx hardhat fork --network localhost --block 6469035')` failed because the command exited with a non-zero code. Pass `{failOnNonZeroExit: false}` to ignore exit code failures. Information about the failure: Code: 1 Stderr: [31mAn unexpected error occurred:[39m ProviderError: ConnectTimeoutError: Connect Timeout Error at HttpProvider.request (/__w/governance-portal-v2/governance-portal-v2/node_modules/hardhat/sr... https://on.cypress.io/exec Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Vote Proxy` Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail

1
CypressError
`cy.exec('yarn fund')` timed out after waiting `60000ms`. https://on.cypress.io/exec Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Vote Proxy` Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail


AssertionError
Timed out retrying after 40000ms: Expected to find content: '/POSTED FEB 15 2022 21:36 UTC/i' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: '/Withdraw from voting contract/' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: '2' within the element: <span.css-1raqk95-DelegatesSystemInfo> but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647499287054' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647513131537' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647526212505' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647541353383' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647867203648' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647867281482' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647872334789' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647872414528' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647874681033' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647874737765' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647874762796' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647874833047' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647875778825' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Comment on the e2e test suite 1647875864587' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'MKR successfully burned in ESM' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647867368620' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647867469043' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647872504335' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647872607037' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647874853630' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647874941600' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647874958858' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647875070051' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647875960743' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #1 - e2e suite - 1647876080518' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Multiple comments #2 - e2e suite - 1647960861820' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Polling Votes' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Transaction Pending' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Transaction Sent!' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find content: 'Transaction Sent' but never did.

1
AssertionError
Timed out retrying after 40000ms: Expected to find element: `[data-testid="delegate-card"]`, but never found it.

1
AssertionError
Timed out retrying after 40000ms: Expected to find element: `[data-testid="poll-overview-card-poll-title"]`, but never found it.

1
AssertionError
Timed out retrying after 40000ms: expected '<label.css-1qp4ca6-DelegatesFilter>' to be 'visible' This element `<label.css-1qp4ca6-DelegatesFilter>` is not visible because its parent `<div>` has CSS property: `display: none`

1
AssertionError
Timed out retrying after 40000ms: expected 23 to be below 18

1
AssertionError
Timed out retrying after 60000ms: Expected to find content: 'Burn Your MKR' but never did.

1
AssertionError
Timed out retrying after 60000ms: Expected to find content: 'MKR successfully burned in ESM' but never did.

1
AssertionError
Timed out retrying after 90000ms: Expected to find content: '0.005' within the element: [ <p.css-1aomy5s-DelegateCard>, 14 more... ] but never did.

1
AssertionError
Timed out retrying after 90000ms: Expected to find content: '0.005' within the element: [ <p.css-9nm8xn-DelegateCard>, 14 more... ] but never did.

1
AssertionError
Timed out retrying after 90000ms: Expected to find content: 'Transaction Sent' but never did.

1
AssertionError
Timed out retrying after 90000ms: Expected to find element: `[data-testid="mkr-input"]`, but never found it.

1
AssertionError
Timed out retrying after 90000ms: Expected to find element: `[data-testid="mkr-supporting"]`, but never found it.

1
AssertionError
Timed out retrying after 90000ms: expected '<p.css-1a65n7e-ExecutiveOverviewCard>' to have text '98,867.974 additional MKR support needed to pass. Expires at .', but the text was '98,870 additional MKR support needed to pass. Expires at .'

1
AssertionError
Timed out retrying after 90000ms: expected '<span.css-dc158g-ExecutiveBalance>' to have text '5.0 MKR', but the text was '3.0 MKR'

**Review by b-pmcg — APPROVED** [review]
LGTM! I merged in develop to get the working test suite. @philipjonsen make sure you are running `yarn hardhat` and in a separate window run `yarn e2e` if you are trying to run the test suite locally

**Comment by philipjonsen** [comment]
hey! yeah, i'm not going to do anything daily, this is stuff I do when i
got time over from business and stuff. Just started a collaboration with
gitlabs and been licensed as red-hat enterprise en all the other stuff you
need to audit och improve other projects :)

Den fre 25 mars 2022 kl 21:15 skrev Phil Bain ***@***.***>:

**Pull request merged**
