### PR TITLE
Feature/sc 1135/implement improved mkr liquidity panel

### PR DESCRIPTION
**Pull request by adamgoth**
### Link to Shortcut ticket:

https://app.shortcut.com/dux-makerdao/story/1135/implement-improved-mkr-liquidity-panel

### What does this PR do?

Adds uniswap v3 and compound liquidity to liquidity panel

Pools protocols together, adds expanding detail sections

### Steps for testing:

Go to exec page, see liquidity updates in sidebar ✨

### CODE REVIEW

**Comment by b-pmcg** [comment]
Looks great, is opening both expandos at the same time intended behavior? Also on goerli the request never resolves and the loading animation goes on forever.

**Comment by adamgoth** [comment]
> Looks great, is opening both expandos at the same time intended behavior? Also on goerli the request never resolves and the loading animation goes on forever.

Expanding/collapsing both was my intention. We could add separate state for each subgroup, but I don't see the point personally. What do you think?

Also I didn't think about goerli... we'd have to find subgraphs/APIs for those pools, if they exist..

**Comment by b-pmcg** [comment]
> Also I didn't think about goerli... we'd have to find subgraphs/APIs for those pools, if they exist..

just meant showing 0 or "n/a" or something if it the request fails, but its probably fine

**Comment by adamgoth** [comment]
> > Also I didn't think about goerli... we'd have to find subgraphs/APIs for those pools, if they exist..
> 
> just meant showing 0 or "n/a" or something if it the request fails, but its probably fine

Makes sense. Just pushed some updates so that it shows 0 on goerli, like the others.

**Pull request merged**
