### PR TITLE
create a wrapper for bignumber.js, add 'no exponent' config option

### PR DESCRIPTION
**Pull request by b-pmcg**
### What does this PR do?

- Clone bignumber and add a global config option to prevent exponent notation
- adds a named export `BigNumberJS` to alleviate confusion with ethers `BigNumber`
- adds test to prevent files from importing BigNumber directly from 'bignumber.js' package

### Steps for testing:
Check vote breakdown page on polls and make sure it doesn't break. This is the one that errored this morning: `https://<previewURL>/polling/Qmbs5Kx5`

### Any additional helpful information?:
https://github.com/MikeMcl/bignumber.js/issues/315#issuecomment-1020673911

### CODE REVIEW

**Review by tyler17 — APPROVED** [review]

**Comment by tyler17** [comment]
LGTM.  I also tested out submitting a ranked choice ballot with 12 options selected, which also used to cause issues with exponential notation.

Wonder if we could add a test that fails if any file other than `lib/bigNumberJs.ts` tries to import bignumber.js

**Review by adamgoth — DISMISSED** [review]
LGTM. One suggestion, not a big deal, but what if we export it as `BigNumberJs` and then always import it as that. That way we don't have a mix of sometimes `BigNumber` is the ethers version and sometimes it's the JS version. You'd just know right away when you see it.

**Comment by b-pmcg** [comment]
> LGTM. I also tested out submitting a ranked choice ballot with 12 options selected, which also used to cause issues with exponential notation.
> 
> Wonder if we could add a test that fails if any file other than `lib/bigNumberJs.ts` tries to import bignumber.js

interesting, how would we do that, with Jest? Or maybe a custom linter rule?

**Comment by b-pmcg** [comment]
> 

That makes sense, so in that case we wouldn't have a default export, right? Just a named export. This would work well with @tyler17's suggestion above.

**Comment by tyler17** [comment]
Not sure, but custom linter rule seems like a good way to do it, I can look into that

**Comment by tyler17** [comment]
was easier to just write a test that reads all the files, what do you think? https://github.com/makerdao/governance-portal-v2/pull/541

**Comment by b-pmcg** [comment]
Oops, I forgot to quote @adamgoth in my comment above. I started implementing this but I realized there are too many places where we use a class called `BigNumber` to make a quick job. However I think it's a good idea so I changed the named export to `BigNumberJS` and in the files where we were already aliasing `BigNumber` as `BigNumberJS`, I just changed the import. Hopefully that's a good compromise and we can slowly phase out importing it as a default export over time.

**Comment by b-pmcg** [comment]
The funny thing is, ethers actually uses BN.js under the hood, but calls it BigNumber. I guess it's far too late to change that now :P

**Review by rafinskipg — APPROVED** [review]

**Pull request merged**
